# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  db:
    container_name: db_vheicles_catalog
    image: mysql:8.0.21
    tty: true # Mesmo que `docker run -t`
    stdin_open: true # Mesmo que `docker run -i`
    restart: always # Restarta a imagem caso algo a faça parar
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: vehicleCatalog
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: password
    

  backend:
    image: backend
    build:
      context: .
      dockerfile: backEnd/Dockerfile
    ports:
      - 5099:5099
    environment:
      - MYSQL_HOST=db
    depends_on:
      - db
    restart: on-failure
